// <auto-generated />
using System;
using KinmuReport.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KinmuReport.Migrations
{
    [DbContext(typeof(AttendanceContext))]
    [Migration("20260213093324_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("KinmuReport.Models.アップロード履歴", b =>
                {
                    b.Property<string>("社員番号")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("対象年月")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("sp版数")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("アップロード日時")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("社員番号", "対象年月")
                        .HasName("アップロード履歴_pkey");

                    b.ToTable("アップロード履歴");
                });

            modelBuilder.Entity("KinmuReport.Models.グループ", b =>
                {
                    b.Property<string>("グループコード")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("グループ名")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("グループコード")
                        .HasName("グループ_pkey");

                    b.ToTable("グループ");
                });

            modelBuilder.Entity("KinmuReport.Models.ロック", b =>
                {
                    b.Property<string>("社員番号")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("対象年月")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ロック日時")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ロック者番号")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("社員番号", "対象年月")
                        .HasName("ロック_pkey");

                    b.HasIndex("ロック者番号");

                    b.ToTable("ロック");
                });

            modelBuilder.Entity("KinmuReport.Models.勤怠", b =>
                {
                    b.Property<string>("社員番号")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("対象年月")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("勤務日")
                        .HasColumnType("TEXT");

                    b.Property<string>("備考")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("出勤日時")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("勤怠区分")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("合計時間")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("所定内時間")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("残業時間")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("深夜残業時間")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("退勤日時")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("社員番号", "対象年月", "勤務日")
                        .HasName("勤怠_pkey");

                    b.ToTable("勤怠");
                });

            modelBuilder.Entity("KinmuReport.Models.社員", b =>
                {
                    b.Property<string>("社員番号")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("adオブジェクトid")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("グループコード")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("パスワードハッシュ")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ログインid")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("権限")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("社員名")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("社員番号")
                        .HasName("社員_pkey");

                    b.HasIndex("グループコード");

                    b.HasIndex(new[] { "ログインid" }, "社員_ログインid_key")
                        .IsUnique();

                    b.ToTable("社員");
                });

            modelBuilder.Entity("KinmuReport.Models.アップロード履歴", b =>
                {
                    b.HasOne("KinmuReport.Models.社員", "社員番号Navigation")
                        .WithMany("アップロード履歴s")
                        .HasForeignKey("社員番号")
                        .IsRequired()
                        .HasConstraintName("アップロード履歴_社員番号_fkey");

                    b.Navigation("社員番号Navigation");
                });

            modelBuilder.Entity("KinmuReport.Models.ロック", b =>
                {
                    b.HasOne("KinmuReport.Models.社員", "ロック者番号Navigation")
                        .WithMany("ロックロック者番号Navigations")
                        .HasForeignKey("ロック者番号")
                        .IsRequired()
                        .HasConstraintName("ロック_ロック者番号_fkey");

                    b.HasOne("KinmuReport.Models.社員", "社員番号Navigation")
                        .WithMany("ロック社員番号Navigations")
                        .HasForeignKey("社員番号")
                        .IsRequired()
                        .HasConstraintName("ロック_社員番号_fkey");

                    b.Navigation("ロック者番号Navigation");

                    b.Navigation("社員番号Navigation");
                });

            modelBuilder.Entity("KinmuReport.Models.勤怠", b =>
                {
                    b.HasOne("KinmuReport.Models.社員", "社員番号Navigation")
                        .WithMany("勤怠s")
                        .HasForeignKey("社員番号")
                        .IsRequired()
                        .HasConstraintName("勤怠_社員番号_fkey");

                    b.Navigation("社員番号Navigation");
                });

            modelBuilder.Entity("KinmuReport.Models.社員", b =>
                {
                    b.HasOne("KinmuReport.Models.グループ", "グループコードNavigation")
                        .WithMany("社員s")
                        .HasForeignKey("グループコード")
                        .HasConstraintName("社員_グループコード_fkey");

                    b.Navigation("グループコードNavigation");
                });

            modelBuilder.Entity("KinmuReport.Models.グループ", b =>
                {
                    b.Navigation("社員s");
                });

            modelBuilder.Entity("KinmuReport.Models.社員", b =>
                {
                    b.Navigation("アップロード履歴s");

                    b.Navigation("ロックロック者番号Navigations");

                    b.Navigation("ロック社員番号Navigations");

                    b.Navigation("勤怠s");
                });
#pragma warning restore 612, 618
        }
    }
}
